version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    depends_on:
      - mqtt
    ports:
      - 8123:8123
    volumes:
      - /home/<user>/.config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      # - "8883:8883" # secure
      # - "9001:9001" # websockets
    volumes:
      - /home/<user>/.config/mosquitto/config:/mosquitto/config:ro
      - /home/<user>/.config/mosquitto/data:/mosquitto/data
      - /home/<user>/.config/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: bridge
