version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    depends_on:
      - mqtt
    ports:
      - "8123:8123"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/home-assistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyACM0

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      # - "8883:8883" # secure
      # - "9001:9001" # websockets
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mqtt/config:/mqtt/config:ro
      - ./config/mqtt/data:/mqtt/data
      - ./config/mqtt/log:/mqtt/log
    restart: unless-stopped
