version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    depends_on:
      - mqtt
    ports:
      - 8123:8123
    volumes:
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      # - "8883:8883" # secure
      # - "9001:9001" # websockets
    volumes:
      - ./config/mqtt/config:/mqtt/config:ro
      - ./config/mqtt/data:/mqtt/data
      - ./config/mqtt/log:/mqtt/log
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
